name: Trivy Scan

on:
  pull_request:
    branches: main

  push:
    branches:
        - main1

  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Directory to scan'
        required: false
        default: './'

jobs:
# Call trivy workflow
  run-trivy:
    name: Run trivy scan
    uses: clouddrove-sandbox/terraform-shared-workflows/.github/workflows/trivy.yml@master
    with:
      working_directory: ${{ github.event.inputs.working_directory || './' }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
