name: Trivy Scan

on:
  push:
    branches:
        - main

  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Directory to scan'
        required: false
        default: '/examples/aws_managed/'

jobs:
# Call trivy workflow
  run-trivy:
    name: Run trivy scan
    uses: clouddrove-sandbox/terraform-shared-workflows/.github/workflows/trivy.yml@master
    with:
      working_directory: ${{ github.event.inputs.working_directory || 'examples/aws_managed/' }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
